### ISSUE TITLE
Fix broken images in /project/35mmfilm

### ISSUE THREAD

**Issue by Issung** [tyPaastor/typedesigns#4]
The images are broken because they have all caps file extensions but in the code are referenced as lower-caps.
Convention is you should keep them all lower caps.

Sometimes git is very annoying when you want to rename a file but only change the capitalisation of letters, may need my help to fix it.

**Comment by tyPaastor** [comment]
Fixed.

Had an issue with source control that made this more of an issue than it needed to be.

**Comment by Issung** [comment]
Yeah I've had it a few times

**Comment by Issung** [comment]
If fixed mark issue as resolved
